from services import context, ogp, share


def build(
    *,
    engine,
    request,
    response_cls,
    render_template,
    public_base_url,
    work_title,
    player_fetish_base_id,
    display_version,
    app_version,
    safe_work_url,
    amazon_associate_id,
    adsense_client='',
    fetish_relations=None,
    error_page,
    record_share_event,
    learning_disabled,
    rate_limit=None,
    environ=None,
):
    return context.seo_context(
        engine=engine,
        request=request,
        Response=response_cls,
        render_template=render_template,
        public_base_url=public_base_url,
        work_title=work_title,
        player_fetish_base_id=player_fetish_base_id,
        display_version=display_version,
        app_version=app_version,
        clean_probability=share.clean_probability,
        result_share_text=share.result_share_text,
        result_tagline=share.result_tagline,
        result_title=share.result_title,
        result_rarity=share.result_rarity,
        generate_ogp_png=ogp.generate_png_safe,
        render_ogp_svg=ogp.render_svg,
        safe_work_url=safe_work_url,
        amazon_associate_id=amazon_associate_id,
        adsense_client=adsense_client,
        fetish_relations=fetish_relations or {},
        error_page=error_page,
        record_share_event=record_share_event,
        learning_disabled=learning_disabled,
        rate_limit=rate_limit or (lambda *_args, **_kwargs: None),
        environ=environ or {},
    )
