"""Build or verify the public recommended-work inventory document."""

import argparse
import json
from pathlib import Path

from engine.work_catalog import materialize_fetish_works, validate_catalog

ROOT = Path(__file__).resolve().parents[1]
DATA_DIR = ROOT / 'data'
OUTPUT_PATH = ROOT / 'docs' / 'RECOMMENDED_WORKS_LIST.md'


def _clean_markdown_text(value):
    return str(value or '').replace('\\', '\\\\').replace('|', '\\|').replace('\n', ' ').strip()


def render_inventory():
    fetishes = json.loads((DATA_DIR / 'fetishes.json').read_text(encoding='utf-8'))
    catalog = json.loads((DATA_DIR / 'work_catalog.json').read_text(encoding='utf-8'))
    validate_catalog(catalog)
    projected = materialize_fetish_works(catalog)
    known_ids = {int(row['id']) for row in fetishes}
    unknown_ids = sorted(set(projected) - known_ids)
    if unknown_ids:
        raise ValueError(f'catalog contains unknown fetish owners: {unknown_ids}')

    lines = [
        '# 現行おすすめ作品一覧',
        '',
        '<!-- Generated by scripts/build_recommended_works_list.py; do not edit manually. -->',
        '',
        '`data/work_catalog.json`の公開fetish projectionを、`data/fetishes.json`のID順で表示します。',
        '作品情報の修正は正規catalogとmanifestへ行い、この文書は生成スクリプトで同期してください。',
        '',
    ]
    for fetish in sorted(fetishes, key=lambda row: int(row['id'])):
        fetish_id = int(fetish['id'])
        lines.append(f'## {fetish_id} {_clean_markdown_text(fetish.get("name"))}')
        works = projected.get(fetish_id, [])
        if not works:
            lines.append('')
            lines.append('- おすすめ作品未登録')
            lines.append('')
            continue
        for work in works:
            title = _clean_markdown_text(work.get('title'))
            url = str(work.get('url') or '').strip()
            identity = f'work_id={work.get("work_id", "")}'
            if work.get('edition_id'):
                identity += f' / edition_id={work["edition_id"]}'
            lines.append('')
            lines.append(f'- {title} | {url or "URL未登録"} | {identity}')
        lines.append('')
    return '\n'.join(lines).rstrip() + '\n'


def main(argv=None):
    parser = argparse.ArgumentParser()
    parser.add_argument('--write', action='store_true')
    args = parser.parse_args(argv)
    rendered = render_inventory()
    if args.write:
        OUTPUT_PATH.write_text(rendered, encoding='utf-8')
        print(f'wrote {OUTPUT_PATH.relative_to(ROOT)}')
        return 0
    if not OUTPUT_PATH.exists() or OUTPUT_PATH.read_text(encoding='utf-8') != rendered:
        print('recommended works list is stale; run python scripts/build_recommended_works_list.py --write')
        return 1
    print('recommended works list: OK')
    return 0


if __name__ == '__main__':
    raise SystemExit(main())
